name: rust-build

on:
  push:
    branches:
      - main

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: build
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: verify
      run: |
        if [ ! -f ./target/x86_64-unknown-linux-musl/release/function ]; then
          echo "Build failed, exiting"
          exit 1
        fi
      shell: bash
